/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MySignatureRouteImport } from './routes/my-signature'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BindersIndexRouteImport } from './routes/binders.index'
import { Route as BindersStatusRouteImport } from './routes/binders.$status'
import { Route as SignBinderIdSignerIdRouteImport } from './routes/sign.$binderId.$signerId'
import { Route as BindersDetailIdRouteImport } from './routes/binders.detail.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MySignatureRoute = MySignatureRouteImport.update({
  id: '/my-signature',
  path: '/my-signature',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BindersIndexRoute = BindersIndexRouteImport.update({
  id: '/binders/',
  path: '/binders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BindersStatusRoute = BindersStatusRouteImport.update({
  id: '/binders/$status',
  path: '/binders/$status',
  getParentRoute: () => rootRouteImport,
} as any)
const SignBinderIdSignerIdRoute = SignBinderIdSignerIdRouteImport.update({
  id: '/sign/$binderId/$signerId',
  path: '/sign/$binderId/$signerId',
  getParentRoute: () => rootRouteImport,
} as any)
const BindersDetailIdRoute = BindersDetailIdRouteImport.update({
  id: '/binders/detail/$id',
  path: '/binders/detail/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-signature': typeof MySignatureRoute
  '/signup': typeof SignupRoute
  '/binders/$status': typeof BindersStatusRoute
  '/binders/': typeof BindersIndexRoute
  '/binders/detail/$id': typeof BindersDetailIdRoute
  '/sign/$binderId/$signerId': typeof SignBinderIdSignerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-signature': typeof MySignatureRoute
  '/signup': typeof SignupRoute
  '/binders/$status': typeof BindersStatusRoute
  '/binders': typeof BindersIndexRoute
  '/binders/detail/$id': typeof BindersDetailIdRoute
  '/sign/$binderId/$signerId': typeof SignBinderIdSignerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/documents': typeof DocumentsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/my-signature': typeof MySignatureRoute
  '/signup': typeof SignupRoute
  '/binders/$status': typeof BindersStatusRoute
  '/binders/': typeof BindersIndexRoute
  '/binders/detail/$id': typeof BindersDetailIdRoute
  '/sign/$binderId/$signerId': typeof SignBinderIdSignerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/documents'
    | '/inbox'
    | '/login'
    | '/my-signature'
    | '/signup'
    | '/binders/$status'
    | '/binders/'
    | '/binders/detail/$id'
    | '/sign/$binderId/$signerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/documents'
    | '/inbox'
    | '/login'
    | '/my-signature'
    | '/signup'
    | '/binders/$status'
    | '/binders'
    | '/binders/detail/$id'
    | '/sign/$binderId/$signerId'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/documents'
    | '/inbox'
    | '/login'
    | '/my-signature'
    | '/signup'
    | '/binders/$status'
    | '/binders/'
    | '/binders/detail/$id'
    | '/sign/$binderId/$signerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  DocumentsRoute: typeof DocumentsRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MySignatureRoute: typeof MySignatureRoute
  SignupRoute: typeof SignupRoute
  BindersStatusRoute: typeof BindersStatusRoute
  BindersIndexRoute: typeof BindersIndexRoute
  BindersDetailIdRoute: typeof BindersDetailIdRoute
  SignBinderIdSignerIdRoute: typeof SignBinderIdSignerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-signature': {
      id: '/my-signature'
      path: '/my-signature'
      fullPath: '/my-signature'
      preLoaderRoute: typeof MySignatureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binders/': {
      id: '/binders/'
      path: '/binders'
      fullPath: '/binders/'
      preLoaderRoute: typeof BindersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binders/$status': {
      id: '/binders/$status'
      path: '/binders/$status'
      fullPath: '/binders/$status'
      preLoaderRoute: typeof BindersStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$binderId/$signerId': {
      id: '/sign/$binderId/$signerId'
      path: '/sign/$binderId/$signerId'
      fullPath: '/sign/$binderId/$signerId'
      preLoaderRoute: typeof SignBinderIdSignerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binders/detail/$id': {
      id: '/binders/detail/$id'
      path: '/binders/detail/$id'
      fullPath: '/binders/detail/$id'
      preLoaderRoute: typeof BindersDetailIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  DocumentsRoute: DocumentsRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MySignatureRoute: MySignatureRoute,
  SignupRoute: SignupRoute,
  BindersStatusRoute: BindersStatusRoute,
  BindersIndexRoute: BindersIndexRoute,
  BindersDetailIdRoute: BindersDetailIdRoute,
  SignBinderIdSignerIdRoute: SignBinderIdSignerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
